version: '3'
services:
  node-app:
    build: .
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_IP=mongo   
      - MONGO_PORT=27017
      
    depends_on:
      - mongo
      - redis
      
  mongo:  
    image: mongo
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
    